### ISSUE TITLE
Why am i getting a error with the default implementation of  (POST) [/facebook/callback] ->

### ISSUE THREAD

**Issue by MrOnyancha** [marcospereira/reddit-bot#2]
![screen shot 2017-02-15 at 2 27 20 pm](https://cloud.githubusercontent.com/assets/5436153/22972606/6594a224-f38b-11e6-8456-6e65d4bf4931.png)

**Comment by marcospereira** [comment]
Hey @MrOnyancha, this was just an experiment I've created some time ago. It is not updated with the possible changes that Facebook made at their API and also it is not intended to be used in production.

The problem above was probably caused by some API change and since this project is not updated, you are seeing the error.

Thanks.
